if_validate: False # If True, enable validation
batch_size: 8 # Batch size for validation
save_model_every_n_epochs: 1 # For the case that if_validate is false. The frequency of saving model. 0 to disable.
check_val_every_n_epochs: 100 # The frequency of running model validation. 0 to disable.
check_val_monitor: "val_loss/absolute_rssd" # The metric to monitor for model validation.
save_top_k_models: 40 # The number of top models to save. 0 to disable.
early_stopping: True # Enable early stopping
early_stopping_patience: 100 # The number of epochs with no improvement after which training will be stopped.