name: spatial-reconstruction

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python and CUDA
  - python=3.9.16
  - cudatoolkit=11.8
  - pip=23.3.1

  # Deep Learning Frameworks
  - pytorch=2.1.1
  - pytorch-lightning=2.0.4

  # Configuration Management
  - pathlib
  - hydra-core
  - time
  - omegaconf
  - tqdm

  # Data Science Libraries
  - numpy
  - pandas
  - scikit-learn
  - scipy

  # Visualization Tools
  - matplotlib
  - seaborn
  - squidpy
  - colorcet

  # Experiment Tracking
  - wandb

  # Pip dependencies
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric