defaults:
    - _self_
    - validation: default
    - test: default
    - general: default
    - train: default
    - model: default
    - experiment: MERFISH_mouse_cortex

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}


